name: Build

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-latest]
        config: [Debug]
        include:
          - os: ubuntu-24.04
            cc: clang
            cxx: clang++
          - os: macos-15
            cc: clang
            cxx: clang++
          - os: windows-latest
            cc: cl.exe
            cxx: cl.exe

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@v5
      with:
        version: 1.12.1

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install llvm
      if: ${{matrix.os == 'macos-15'}}
      run: |
        brew install llvm
        echo $(brew --prefix llvm@18)/bin
        echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.profile
        export PATH=$(brew --prefix llvm@18)/bin:$PATH && echo "PATH=$PATH" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Generate build system
      run: cmake -B ${{github.workspace}}/build
                 -G Ninja
                 -DCMAKE_C_COMPILER:STRING=${{matrix.cc}}
                 -DCMAKE_CXX_COMPILER:STRING=${{matrix.cxx}}
                 -DCMAKE_BUILD_TYPE:STRING=${{matrix.config}}

    - name: Build targets
      run: cmake --build ${{github.workspace}}/build
                 --config ${{matrix.config}}

    - name: Perform tests
      run: ctest --test-dir ${{github.workspace}}/build
                 --build-config ${{matrix.config}}
                 --verbose

    - name: Install package
      run: cmake --install ${{github.workspace}}/build
                 --config ${{matrix.config}}
                 --prefix ${{github.workspace}}/install
           
    - name: Create package
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{matrix.config}} -G ZIP -V
